apiVersion: v1
kind: Service
metadata:
  name: test-headless-1
  namespace: default
spec:
 selector:               
   scal: "1"
 clusterIP: None         
 ports:
 -  name: server
    port: 80
    targetPort: 80
